scrape_configs:
  - job_name: prometheus
    scrape_interval: 1s
    scrape_timeout: 1s
    scheme: http
    metrics_path: "/federate"
    honor_labels: true
    params:
      "match[]":
        - '{job="kcd-server"}'
        - '{job="kcd-server-default"}'
        - '{job="kcd-node-exporter"}'
    static_configs:
      - targets:
          - kcd-prometheus:9090
  - job_name: secondary-prometheus
    scrape_interval: 1s
    scrape_timeout: 1s
    scheme: http
    metrics_path: "/federate"
    honor_labels: true
    params:
      "match[]":
        - '{job="kcd-pushgateway"}'
    static_configs:
      - targets:
          # Running in the same docker network so just the default port
          # 9090 instead of the port exposed in the host network
          - kcd-secondary-prometheus:9090
