alerting:
    alertmanagers:
      - static_configs:
        - targets:
          - kcd-alertmanager:9093
rule_files:
  - /etc/rules/rules.yml
scrape_configs:
  - job_name: kcd-server
    scrape_interval: 1s
    scrape_timeout: 1s
    scheme: http
    static_configs:
      - targets:
          - kcd-server:8089
        labels:
          kcd_server: docker
  - job_name: kcd-server-default
    scrape_interval: 1s
    scrape_timeout: 1s
    scheme: http
    metrics_path: /default-metrics
    static_configs:
      - targets:
          - kcd-server:8089
        labels:
          kcd_server: docker
  - job_name: kcd-node-exporter
    scrape_interval: 1s
    scrape_timeout: 1s
    scheme: http
    static_configs:
      - targets:
          - kcd-node-exporter:9100
        labels:
          kcd_server: docker
