{
 "title": "Suggestions",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Quantiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Summary Quantile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "expr": "delay_summary", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Histogram Quantile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(delay_histogram_bucket[1m])) by (le))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(delay_histogram_bucket[5m])) by (le))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(delay_histogram_bucket[5m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "ALERTS{alertstate=\"firing\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active HTTP connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      { "expr": "present_connections", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Heavy Load (> 5)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      { "expr": "present_connections > 5", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "API Invocation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Invoke Success",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "api_invoke_count{success=\"true\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Invoke Failure",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "api_invoke_count{success=\"false\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Success ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      { "expr": "api_success_percentage", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}